In [18]:
import torch
import torch.nn as nn 

In [19]:
torch.manual_seed(42)  # random state of pytorch
neuron = nn.Linear(in_features=3,out_features=1)


In [20]:
inputs = torch.tensor([1.0,2.0,3.0])

In [21]:
output = neuron(inputs)

In [22]:
print(output)

tensor([1.5244], grad_fn=<ViewBackward0>)


In [23]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [24]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [25]:
# -- verify 

total = neuron.weight@inputs +neuron.bias

print(total)

tensor([1.5244], grad_fn=<AddBackward0>)
