In [6]:
import numpy as np
import time

## difference between the numpy array and the list 


In [7]:

number = 10_000_000
py_list = list(range(number))
start = time.time()
py_sq = [x**2 for x in range(number)]
end = time.time()
print(f"time of python list is = {end - start}")

np_array = np.array(py_list)
start = time.time()
np_sq = np_array **2
end = time.time()
print(f"time of python list is = {end - start}")

time of python list is = 1.0762288570404053
time of python list is = 0.036768198013305664


store the data in contigous memory block

In [8]:
# Memory Usage 
import sys

print(f"size of the python list : {sys.getsizeof(py_list)}")
print(f"size of the python list : {np_array.nbytes}")

size of the python list : 80000056
size of the python list : 80000000


reason why the Numpy is fast 
C intergrate , vector operations 


In [9]:
# create the array 

In [10]:
arr = np.array([1,2,3,4,6])
print(arr,arr.dtype)

arr1 = np.array([1,2,3,4,"Gaurav"])
print(arr1,arr1.dtype)

[1 2 3 4 6] int64
['1' '2' '3' '4' 'Gaurav'] <U21


In [11]:
# 2D array 
twoD_array = np.array([[1,2,3],[4,5,6]])
print(twoD_array,"\n",twoD_array.shape)

[[1 2 3]
 [4 5 6]] 
 (2, 3)


In [12]:
# create from scratch 

array = np.zeros((3,5),dtype=int)
print(array,"\n")

array1 = np.ones((3,5),dtype=int)
print(array1,"\n")


array2 = np.full((3,5),5)
print(array2)

# identity matrix 

array3 = np.eye((3))
print(array3)

# range 

array4 = np.arange(0,20,2)
print(array4)

#linpace 


array5 = np.linspace(1,100,4,dtype=int)
print(array5)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[  1  34  67 100]


## PROPERTY


In [13]:
lst = np.array([1,2,3,4,5,6])
# dimension
print(lst.shape)

# total element 
print(lst.size)
# no of dimension 
print(lst.ndim)

# change type 
float_lst = lst.astype(np.float64)
print(float_lst,float_lst.dtype)

(6,)
6
1
[1. 2. 3. 4. 5. 6.] float64


# Property


In [14]:
arr =np.array([[1,2,3],[4,5,6]])
change = arr.reshape(3,2)
print(arr,"\n\n",arr.shape)
print(change,"\n\n",change.shape)
# flatten arr

flatten = arr.flatten()
print(flatten)

[[1 2 3]
 [4 5 6]] 

 (2, 3)
[[1 2]
 [3 4]
 [5 6]] 

 (3, 2)
[1 2 3 4 5 6]


difference between the slicing in np array and list

In the list when we are slice the list it create the copy of the list 
but in the case of np_array it did not create the copy it only show the <b>view</b> 

In [16]:
# let check with code 
arr= [1,2,3,4,5,6]
sub_array = arr[1:3]
print(f" the is original slice {sub_array}")
sub_array[1] = 11
print(f" the is sub array after the change {sub_array}")
print( arr)


# In the np_array 
arr_np= np.array([1,2,3,4,5,6])
sub_array1 =arr_np[1:3]
print(f" the is original slice {sub_array1} is the np array")
sub_array1[1] = 11
print(f" the is sub array after the change {sub_array1} is the np array ")
print( arr_np,arr_np.dtype)


 the is original slice [2, 3]
 the is sub array after the change [2, 11]
[1, 2, 3, 4, 5, 6]
 the is original slice [2 3] is the np array
 the is sub array after the change [ 2 11] is the np array 
[ 1  2 11  4  5  6] int64


## Dtype is the Np 
for the integer there  are
int8   - it store the 3 digit
int16  - it store the 5 digit
int32  it store the 10 digit 
int64   - And So on
int128

Same of float 
--> It also store the complex number --> a +bi and the dtype in complex 128 for the 64 bit OP system 

In [22]:
# Complex number 
arr = np.array([5+12j])
print(arr,arr.dtype)
# WE ALSO PREFORM THE OPERATION

[5.+12.j] complex128


## MULTIDIMENSIONAL ARRAY

In [ ]:
# WE ARE GENERALLY USE THE MULTIDIMENSIONAL ARRAY FOR STORE THE IMAGE 

# AXES == DIMENSION




# 1D --> 1 AXIS (axis 0)
# 2D --> 2 AXIS
- axis 0: row (to access vertical values)
- axis 1: column (to access horizontal values)

# 3D --> 3 AXIS
- axis 0: depth/layer
- axis 1: row in each layer
- axis 2: column

In [24]:
# Multidimensional array 
# 1D array
arr1D = np.array([1, 2, 3])
print(arr1D.ndim) # 1
# 2D array (matrix)
arr2D = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr2D.ndim) # 2
# 3D array (tensor)
arr3D = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr3D.ndim) # 3

1
2
3


In [38]:
# 3d array 
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],]) #3d array 
print(arr3d.ndim,arr3d.shape)
print(arr3d)
print(arr3d[1,1,1])
print(arr3d[:,0,:])# first row from the array 
print(arr3d[:,:,0])# first col from the array 

arr3d[:,0,:] = 100
print(arr3d)

3 (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
[[1 2]
 [5 6]]
[[1 3]
 [5 7]]
[[[100 100]
  [  3   4]]

 [[100 100]
  [  7   8]]]


## Vectorization & Broadcasting in NumPy


Vectorization and Broadcasting in NumPy are two of the most powerful features for fast numerical computations.
### Vectorization
<b>Vectorization means performing operations on entire arrays at once without explicit</b><br>
Python loops.<br>
- NumPy uses C-level implementations internally → much faster than Python loops.
- Makes code shorter, cleaner, and faster


### Broadcasting <br>
Broadcasting allows NumPy to automatically expand arrays of different shapes so<br>
that arithmetic operations can be performed. It’s basically scaling arrays without using<br>
extra memory.<br>
- No need to manually reshape arrays.
- Useful for combining arrays of different dimensions.
<br>
<b>Broadcasting Rules</b><br>
Broadcasting can only take place when the arrays are of compatible shape. So NumPy <br>
compares shapes of arrays from right to left. For the array to be compatible, all<br>
dimensions must either be:

- • Equal, or
- • 1, or
- • Missing (smaller array can be “stretched”

In [39]:
arr = np.array([1, 2, 3, 4, 5])
sq_arr = arr ** 2 # Square of all nums
print(sq_arr)
arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2) # Sum of 2 arrays

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [40]:
arr_mul10 = arr * 10 # Multiply by 10 to all nums
print(arr_mul10)
# Broadcasting with a Vector
arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)


[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


## Vector Normalization 

A quite common example of broadcasting in Vector Normalization. This is very<br>
common in machine learning and data preprocessing.<br>
Let’s take an example of Standard Vector Normalization i.e. transforming an array<br>
such that it has:<br>
- • mean = 0
- • standard deviation = 1
For each element xi in vector, xi<br>
normalized = (xi − μ)/σ<br>
Where:<br>
- • μ = mean of the vector (or column)
- • σ = standard deviatio

In [41]:
# Standard Vector Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(normalized_arr)
# Column wise Normalization
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr - mean) / std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
